#include <stdio.h>
#include <stdlib.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "assign02.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to

int rgbColour = 4; // colour for RGB LED

// Must declare the main assembly entry point before use.
void main_asm();

// Initialise a GPIO pin – see SDK for detail on gpio_init()
void asm_gpio_init(uint pin) {
    gpio_init(pin);
}

// Set direction of a GPIO pin – see SDK for detail on gpio_set_dir()
void asm_gpio_set_dir(uint pin, bool out) {
    gpio_set_dir(pin, out);
}

// Enable falling-edge interrupt – see SDK for detail on gpio_set_irq_enabled()
void asm_gpio_set_irq_fall(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_FALL, true);
}

// Enable rising-edge interrupt – see SDK for detail on gpio_set_irq_enabled()
void asm_gpio_set_irq_rise(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_RISE, true);
}

void addToSequence() {
    //TODO
}

void displaySequence() {
    //TODO
}

/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

/**
 * @brief RGB LED colours indicating the stages of the games
 *        Sets the colour of the RGB LED on the MAKER-PI-PICO
 *        based on the players current stage/progress in the game.
 *        using one of the RP2040 built-in PIO controllers.
 * 
 * @param rgbColour number indicating the colour we want to set the RGB LED to 
 */
void setRgbStatus(int rgbColour) {
    if(rgbColour == 4) // If game is not in progress set RGB LED to blue
        put_pixel(urgb_u32(0x00, 0x00, 0xFF));
    else {
        // Game is in progress...
        if(rgbColour == 3)
            put_pixel(urgb_u32(0x00, 0x7F, 0x00)); // If game has started and player has 3 lives set the RGB LED to green
        else if(rgbColour == 2)
            put_pixel(urgb_u32(0xFF, 0xFF, 0x00)); // If game has started and player has 2 lives set the RGB LED to yellow
        else if(rgbColour == 1)
            put_pixel(urgb_u32(0xFF, 0xD3, 0x00)); // If game has started and player has 1 lives set the RGB LED to orange
        else if(rgbColour == 0)
            put_pixel(urgb_u32(0x7F, 0x00, 0x00)); // If game has started and player has 0 lives set the RGB LED to red, this means it is game over
    }
}

// Global variables
char buffer[5];
char check[5];

// Character array for the alphanumeric digits & letters
char alphanumericCharacters[] = {
    // Alphanumeric letters A - Z
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
    // Alphanumeric digits 0 - 9
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'};

// Character array for the morse code digits & letters
char MorseCodeCharacters[36][5] = { 
    // Morse code for the letters A - Z
    ".-", "-...", "-.-.", "-..", ".", "..-.", "--.", "....",
    "..", ".---", "-.-", ".-..", "--", "-.", "---", ".--.",
    "--.-", ".-.", "...", "-", "..-", "...-", ".--", "-..-",
    "-.--", "--..",
    // Morse code for the digits 0-9
    "-----", ".----", "..---", "...--", "....-", ".....",
    "-....", "--...", "---..", "----."};

void welcome_message_banner() {
  printf("\n+--------------------------------------------------------+\n");
  printf("|              ASSIGNMENT #02      Group 11              |\n");
  printf("+--------------------------------------------------------+\n");
  printf("|    +       +  +------+  +------+   +----+  +------+    |\n");
  printf("|    | \\   / |  |      |  |       +  |       |           |\n");
  printf("|    |   +   |  |      |  |------+   +----+  |----+      |\n");
  printf("|    |       |  |      |  |     \\         |  |           |\n");
  printf("|    +       +  +------+  +      +   +----+  +------+    |\n");
  printf("|                                                        |\n");
  printf("|         +------+  +------+  +----+    +------+         |\n");
  printf("|         |         |      |  |     \\   |                |\n");
  printf("|         |         |      |  |      +  |----+           |\n");
  printf("|         |         |      |  |     /   |                |\n");
  printf("|         +------+  +------+  +----+    +------+         |\n");
  printf("|                                                        |\n");
  printf("|          +------+    ^    +       +  +------+          |\n");
  printf("|          |         /   \\  | \\   / |  |                 |\n");
  printf("|          |   +--|  |---|  |   +   |  |----+            |\n");
  printf("|          |      |  |   |  |       |  |                 |\n");;
  printf("|          +------+  +   +  +       +  +------+          |\n");
  printf("+--------------------------------------------------------+\n");
  printf("|       TO BEGIN, PRESS ON GP21 TO ENTER SEQUENCE        |\n");
  printf("|         \".----\" - LEVEL 01 - CHARACTERS (EASY)         |\n");
  printf("|         \"..---\" - LEVEL 02 - CHARACTERS (HARD)         |\n");
  printf("+--------------------------------------------------------+\n");
  printf("Rules:\n");
  printf("1. Enter the character displayed in morse code.\n");
  printf("2. If you get the character correct you win a life (max number of lives: 3).\n");
  printf("3. Otherwise you lose a life. The LED will show you how many lives you have.\n");
  printf("4. If you do not enter a character for a period of 9 seconds, the game will reset.\n");
  printf("5. If you end up with zero lives, you lose.\n");
  printf("\nCHOOSE A LEVEL FROM THE ONES SHOWN ABOVE: ");
}

/*
 * Main entry point for the code - simply calls the main assembly function.
 */
int main() {

    // Initialise all STDIO as we will be using the GPIOs
    stdio_init_all();

    // Initialise the PIO interface with the RGB code in the assign02.pio file containing the ws2812 code
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);

    // Game is not in progress so set the RGB LED to blue - need to edit intensity
    setRgbStatus(rgbColour);
    sleep_ms(500);

    main_asm();

    return(0);
}
